# Generated by Django 4.2.1 on 2024-11-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neapp', '0002_alter_post_options_post_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
