# Generated by Django 4.2.1 on 2024-11-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neapp', '0003_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
